version: '3.8'

services:
  web:
    build: .
    command: python main.py run
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres:13 
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=pynance_db
    networks:
      - mynetwork  

volumes:
  data:

networks:
  mynetwork: